/// Flutter icons MenuIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MenuIcon
///      fonts:
///       - asset: fonts/MenuIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MenuIcon {
  MenuIcon._();

  static const _kFontFam = 'MenuIcon';
  static const String? _kFontPkg = null;

  static const IconData menu_icon =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
